package org.unlaxer.dsl;

import java.io.IOException;
import java.io.PrintStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.HashMap;
import java.util.Map;
import org.unlaxer.dsl.bootstrap.UBNFMapper;
import org.unlaxer.dsl.codegen.rust.RustBackend;

/** Experimental subcommand; the existing Java flag-based CLI stays unchanged. */
final class RustGenerateCommand {
    private RustGenerateCommand() {}

    static int run(String[] args, PrintStream out, PrintStream err) {
        Map<String, String> options = new HashMap<>();
        boolean check = false;
        try {
            for (int i = 1; i < args.length; i++) {
                String option = args[i];
                if (option.equals("--help")) {
                    out.println("Usage: generate --target rust --grammar <file.ubnf> --output <module-directory> [--check]");
                    return 0;
                }
                if (option.equals("--check")) {
                    if (check) throw new IllegalArgumentException("duplicate --check");
                    check = true;
                    continue;
                }
                if (!java.util.Set.of("--target", "--grammar", "--output").contains(option)
                    || i + 1 == args.length || args[i + 1].startsWith("--")) {
                    throw new IllegalArgumentException("unknown or incomplete option " + option);
                }
                if (options.putIfAbsent(option, args[++i]) != null) throw new IllegalArgumentException("duplicate " + option);
            }
            if (!"rust".equals(options.get("--target")) || !options.containsKey("--grammar") || !options.containsKey("--output")) {
                throw new IllegalArgumentException("required: --target rust --grammar <file.ubnf> --output <directory>");
            }
        } catch (IllegalArgumentException error) {
            err.println(error.getMessage());
            return CodegenMain.EXIT_CLI_ERROR;
        }
        try {
            var file = UBNFMapper.parse(Files.readString(Path.of(options.get("--grammar"))));
            if (file.grammars().size() != 1) throw new IllegalArgumentException("Rust subset requires exactly one grammar");
            var generated = new RustBackend().generate(file.grammars().get(0));
            Path output = Path.of(options.get("--output"));
            if (Files.isSymbolicLink(output)) throw new IOException("output directory must not be a symbolic link");
            // Preflight every file before writing: never replace handwritten code or follow file symlinks.
            for (var artifact : generated) {
                Path destination = output.resolve(artifact.relativePath());
                if (Files.isSymbolicLink(destination)) throw new IOException("refusing symbolic link " + destination);
                if (check) {
                    if (!Files.isRegularFile(destination) || !Files.readString(destination).equals(artifact.content())) {
                        throw new IOException("generated file differs: " + destination);
                    }
                } else if (Files.exists(destination)
                    && (!Files.isRegularFile(destination) || !Files.readString(destination).startsWith("// Generated by unlaxer RustBackend."))) {
                    throw new IOException("refusing to overwrite non-generated file " + destination);
                }
            }
            if (!check) {
                Files.createDirectories(output);
                for (var artifact : generated) Files.writeString(output.resolve(artifact.relativePath()), artifact.content());
            }
            out.println((check ? "Verified " : "Generated ") + generated.size() + " Rust module files in " + output);
            return CodegenMain.EXIT_OK;
        } catch (IllegalArgumentException error) {
            err.println(error.getMessage());
            return CodegenMain.EXIT_VALIDATION_ERROR;
        } catch (IOException error) {
            err.println(error.getMessage());
            return CodegenMain.EXIT_GENERATION_ERROR;
        }
    }
}
