//! Rust-native emission of the same modules as the Java RustBackend.
//!
//! This crate accepts normalized IR, not UBNF source. Frontends must validate
//! grammar semantics (including capture shapes, nullability and left recursion).
pub mod ir;
mod validate;
pub use ir::*;
use std::fmt::Write;

const HEADER: &str = "// Generated by unlaxer RustBackend. Regenerate; do not edit.\n";

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedFile {
    pub relative_path: String,
    pub content: String,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GenerateError(pub String);

impl std::fmt::Display for GenerateError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.0)
    }
}
impl std::error::Error for GenerateError {}

/// Validate structural IR and emit five files. No filesystem writes or Java calls.
pub fn generate(ir: &GrammarIr) -> Result<Vec<GeneratedFile>, GenerateError> {
    validate::validate(ir)?;
    Ok([
        (
            "mod.rs",
            format!("{HEADER}pub mod ast;\npub mod parser;\npub mod mapper;\npub mod evaluator;\n"),
        ),
        ("ast.rs", ast(ir)),
        ("parser.rs", parser(ir)),
        ("mapper.rs", mapper(ir)),
        ("evaluator.rs", evaluator(ir)),
    ]
    .into_iter()
    .map(|(path, content)| GeneratedFile {
        relative_path: path.into(),
        content,
    })
    .collect())
}

fn mappings(ir: &GrammarIr) -> Vec<&Mapping> {
    let mut result = Vec::new();
    for mapping in ir.rules.iter().filter_map(|r| r.mapping.as_ref()) {
        if !result.contains(&mapping) {
            result.push(mapping);
        }
    }
    result
}

fn has_values(ir: &GrammarIr) -> bool {
    mappings(ir)
        .iter()
        .flat_map(|m| &m.fields)
        .any(|f| f.kind == Kind::Value)
}

fn ast(ir: &GrammarIr) -> String {
    let mut out = String::from(HEADER);
    out.push_str("use unlaxer_runtime::{Span, json_string};\n\n");
    if has_values(ir) {
        out.push_str("#[derive(Debug, Clone, PartialEq)]\npub enum AstValue {\n    Text { text: String, span: Span },\n    Node(Box<Ast>),\n}\n\nimpl AstValue {\n    pub fn span(&self) -> Span {\n        match self {\n            Self::Text { span, .. } => *span,\n            Self::Node(node) => node.span(),\n        }\n    }\n\n    pub fn canonical_json(&self) -> String {\n        match self {\n            Self::Text { text, .. } => json_string(text),\n            Self::Node(node) => node.canonical_json(),\n        }\n    }\n}\n\n");
    }
    out.push_str("#[allow(non_snake_case, non_camel_case_types)]\n#[derive(Debug, Clone, PartialEq)]\npub enum Ast {\n");
    for mapping in mappings(ir) {
        write!(out, "    r#{} {{ span: Span", mapping.name).unwrap();
        for field in &mapping.fields {
            write!(out, ", r#{}: {}", field.name, field_type(field, false)).unwrap();
        }
        out.push_str(" },\n");
    }
    out.push_str("}\n\n#[allow(non_snake_case)]\nimpl Ast {\n    pub fn span(&self) -> Span {\n        match self {\n");
    for mapping in mappings(ir) {
        writeln!(
            out,
            "            Self::r#{} {{ span, .. }} => *span,",
            mapping.name
        )
        .unwrap();
    }
    out.push_str(
        "        }\n    }\n\n    pub fn canonical_json(&self) -> String {\n        match self {\n",
    );
    for mapping in mappings(ir) {
        writeln!(out, "            {} => {{", pattern(mapping, "Self")).unwrap();
        out.push_str("                let fields: Vec<String> = vec![\n");
        for field in &mapping.fields {
            writeln!(
                out,
                "                    format!(\"{{}}:{{}}\", json_string({}), {}),",
                quote(&field.name),
                field_json(field)
            )
            .unwrap();
        }
        out.push_str("                ];\n                format!(\"{{\\\"type\\\":{},\\\"span\\\":[{},{}],\\\"fields\\\":{{{}}}}}\", json_string(");
        out.push_str(&quote(&mapping.name));
        out.push_str("), span.start, span.end, fields.join(\",\"))\n            },\n");
    }
    out.push_str("        }\n    }\n}\n");
    out
}

fn parser(ir: &GrammarIr) -> String {
    let mut out = String::from(HEADER);
    out.push_str("use std::sync::OnceLock;\n#[cfg(test)]\nuse std::sync::atomic::{AtomicUsize, Ordering};\nuse unlaxer_runtime::{Expr, Rule, SharedGrammar, Tree, ParseError, ParseDiagnostic, ParseContext, ParseResult, Parser};\n\n#[cfg(test)]\nstatic GRAMMAR_INITIALIZATIONS: AtomicUsize = AtomicUsize::new(0);\n\npub struct GeneratedParser;\n\nimpl Parser for GeneratedParser {\n    fn parse(&self, context: &mut ParseContext<'_>) -> ParseResult {\n        parse_context(context)\n    }\n}\n\npub fn parse_tree(source: &str) -> Result<Tree, ParseError> {\n    parse_tree_detailed(source).map_err(|diagnostic| diagnostic.farthest)\n}\n\n/// Compatibility snapshot of the generated rules. Parsing uses `grammar()` and does not clone them.\npub fn rules() -> Vec<Rule> {\n    grammar().iter().cloned().collect()\n}\n\n/// Immutable grammar graph, initialized once and shared by every parse.\npub fn grammar() -> &'static SharedGrammar {\n    static GRAMMAR: OnceLock<SharedGrammar> = OnceLock::new();\n    GRAMMAR.get_or_init(|| {\n        #[cfg(test)]\n        GRAMMAR_INITIALIZATIONS.fetch_add(1, Ordering::Relaxed);\n        vec![\n");
    for rule in &ir.rules {
        writeln!(
            out,
            "            Rule {{ name: {}, expression: {} }},",
            quote(&rule.name),
            expression(&rule.body)
        )
        .unwrap();
    }
    out.push_str("        ].into()\n    })\n}\n\n/// Test-only evidence for the process-wide `OnceLock` construction contract.\n#[cfg(test)]\n#[doc(hidden)]\npub fn grammar_initialization_count() -> usize {\n    GRAMMAR_INITIALIZATIONS.load(Ordering::Relaxed)\n}\n\npub fn parse_context(context: &mut ParseContext<'_>) -> ParseResult {\n    context.parse_shared_grammar(grammar(), ");
    write!(out, "{}, {})\n}}\n", ir.root, ir.java_whitespace).unwrap();
    out.push_str("\npub fn parse_tree_detailed(source: &str) -> Result<Tree, ParseDiagnostic> {\n    unlaxer_runtime::parse_detailed_shared(grammar(), ");
    write!(out, "{}, {}, source)\n}}\n", ir.root, ir.java_whitespace).unwrap();
    let mut operators: Vec<_> = ir
        .rules
        .iter()
        .filter_map(|r| r.operator.map(|op| (r, op)))
        .collect();
    if !operators.is_empty() {
        out.push_str("\n/// Descriptive metadata; parsing precedence follows the grammar's rule graph.\n#[derive(Debug, Clone, Copy, PartialEq, Eq)]\npub enum Associativity { ");
        out.push_str(
            if operators
                .iter()
                .any(|(_, op)| op.associativity == Associativity::Right)
            {
                "Left, Right, None"
            } else {
                "Left, None"
            },
        );
        out.push_str(" }\n#[derive(Debug, Clone, Copy, PartialEq, Eq)]\npub struct OperatorSpec {\n    pub rule: &'static str,\n    pub precedence: i32,\n    pub associativity: Associativity,\n}\npub const OPERATORS: &[OperatorSpec] = &[\n");
        operators
            .sort_by(|(a, x), (b, y)| x.precedence.cmp(&y.precedence).then(a.name.cmp(&b.name)));
        for (rule, op) in operators {
            writeln!(out, "    OperatorSpec {{ rule: {}, precedence: {}, associativity: Associativity::{} }},", quote(&rule.name), op.precedence, match op.associativity { Associativity::Left => "Left", Associativity::Right => "Right", Associativity::None => "None" }).unwrap();
        }
        out.push_str("];\n");
    }
    let catalogs: Vec<_> = ir
        .rules
        .iter()
        .filter_map(|rule| rule.catalog.as_ref().map(|catalog| (rule, catalog)))
        .collect();
    if !catalogs.is_empty() {
        out.push_str("\n/// Catalog targets retained for future context-aware tooling.\n#[derive(Debug, Clone, Copy, PartialEq, Eq)]\npub struct CatalogSpec {\n    pub rule: &'static str,\n    pub context: &'static str,\n    pub captures: &'static [&'static str],\n}\npub const CATALOGS: &[CatalogSpec] = &[\n");
        for (rule, catalog) in catalogs {
            let captures = catalog
                .captures
                .iter()
                .map(|name| quote(name))
                .collect::<Vec<_>>()
                .join(", ");
            writeln!(
                out,
                "    CatalogSpec {{ rule: {}, context: {}, captures: &[{}] }},",
                quote(&rule.name),
                quote(&catalog.context),
                captures
            )
            .unwrap();
        }
        out.push_str("];\n");
    }
    out
}

fn expression(expr: &Expression) -> String {
    use Expression::*;
    match expr {
        RuleEffects { child, effects } => {
            let scope = effects.scope_mode.map_or_else(
                || "None".into(),
                |mode| format!("Some(unlaxer_runtime::ScopeMode::{mode:?})"),
            );
            let declares = effects.declares.as_ref().map_or_else(|| "None".into(), |decl| format!("Some(unlaxer_runtime::Declaration {{ symbol_capture: {}, description: {} }})", quote(&decl.symbol_capture), option_text(decl.description.as_deref())));
            format!("{}.rule_effects(unlaxer_runtime::RuleEffects {{ scope_mode: {scope}, declares: {declares}, backref: {} }})", expression(child), option_text(effects.backref.as_deref()))
        }
        Literal(s) => format!("Expr::Literal({})", quote(s)),
        NumberToken => "Expr::Number".into(),
        IdentifierToken => "Expr::Identifier".into(),
        QuotedToken(q) => format!("Expr::Quoted('\\u{{{:x}}}')", u32::from(*q)),
        CodeStartToken => "Expr::CodeStart".into(),
        CodeEndToken => "Expr::CodeEnd".into(),
        AnyToken => "Expr::Any".into(),
        EofToken => "Expr::Eof".into(),
        EmptyToken => "Expr::JavaEmpty".into(),
        CharRangeToken { min, max } => format!(
            "Expr::CharRange('\\u{{{:x}}}', '\\u{{{:x}}}')",
            u32::from(*min),
            u32::from(*max)
        ),
        ExceptToken(s) => format!("Expr::Except({})", quote(s)),
        UntilToken(s) => format!("Expr::JavaUntil({})", quote(s)),
        LookaheadToken { pattern, positive } => format!(
            "Expr::JavaLookahead {{ pattern: {}, positive: {positive} }}",
            quote(pattern)
        ),
        Reference(id) => format!("Expr::Rule({id})"),
        Sequence(items) => format!("Expr::Sequence(vec![{}])", expressions(items)),
        Delimited(child) => format!("Expr::Sequence(vec![{}])", expression(child)),
        TextValue(child) => format!("{}.text_value()", expression(child)),
        ValueBoundary(child) => format!("{}.value_boundary()", expression(child)),
        TriviaScope {
            child,
            java_whitespace,
        } => {
            format!("{}.trivia_scope({java_whitespace})", expression(child))
        }
        Choice(items) => format!("Expr::Choice(vec![{}])", expressions(items)),
        Capture {
            name,
            expression: child,
        } => format!(
            "Expr::Capture({}, Box::new({}))",
            quote(name),
            expression(child)
        ),
        OptionalExpr(child) => format!("{}.optional_java()", expression(child)),
        Repeat { child, min, max } => format!(
            "{}.repeat_java({min}, {})",
            expression(child),
            max.map_or_else(|| "None".into(), |max| format!("Some({max})"))
        ),
        Separated { child, separator } => format!(
            "{}.separated_by({})",
            expression(child),
            expression(separator)
        ),
    }
}

fn option_text(value: Option<&str>) -> String {
    value.map_or_else(|| "None".into(), |text| format!("Some({})", quote(text)))
}

fn expressions(items: &[Expression]) -> String {
    items.iter().map(expression).collect::<Vec<_>>().join(", ")
}

fn mapper(ir: &GrammarIr) -> String {
    let mut out = String::from(HEADER);
    if has_values(ir) {
        out.push_str("use super::ast::AstValue;\n");
    }
    out.push_str("use super::ast::Ast;\nuse unlaxer_runtime::Tree;\n\npub fn map(tree: &Tree) -> Result<Ast, String> {\n    required(map_node(tree, tree.root)?, \"root\")\n}\n\nfn required<T>(mut values: Vec<T>, name: &str) -> Result<T, String> {\n    if values.len() != 1 { return Err(format!(\"expected one value for {name}, got {}\", values.len())); }\n    Ok(values.remove(0))\n}\n\nfn map_nodes(tree: &Tree, ids: &[usize]) -> Result<Vec<Ast>, String> {\n    let mut found = Vec::new();\n    for &id in ids { found.extend(map_node(tree, id)?); }\n    Ok(found)\n}\n");
    if has_values(ir) {
        out.push_str("\nfn map_values(tree: &Tree, ids: &[usize]) -> Result<Vec<AstValue>, String> {\n    let mut found = Vec::new();\n    for &id in ids {\n        let node = &tree.nodes[id];\n        match node.rule {\n            unlaxer_runtime::TEXT_VALUE_RULE => found.push(AstValue::Text {\n                text: unlaxer_runtime::java_capture_text(tree.text(node.span)).to_owned(),\n                span: node.span,\n            }),\n");
        out.push_str("            unlaxer_runtime::VALUE_BOUNDARY_RULE => {\n                let values = map_values(tree, &node.children)?;\n                if !values.is_empty() && values.iter().all(|value| matches!(value, AstValue::Text { .. })) {\n                    found.push(AstValue::Text {\n                        text: unlaxer_runtime::java_capture_text(tree.text(node.span)).to_owned(),\n                        span: node.span,\n                    });\n                } else {\n                    found.extend(values);\n                }\n            },\n");
        let ids: Vec<_> = ir
            .rules
            .iter()
            .enumerate()
            .filter(|(_, r)| r.mapping.is_some())
            .map(|(id, _)| id.to_string())
            .collect();
        writeln!(out, "            {} => found.extend(map_node(tree, id)?.into_iter().map(|node| AstValue::Node(Box::new(node)))),", ids.join(" | ")).unwrap();
        out.push_str("            _ => found.extend(map_values(tree, &node.children)?),\n        }\n    }\n    Ok(found)\n}\n");
    }
    if mappings(ir)
        .iter()
        .flat_map(|m| &m.fields)
        .any(|f| f.cardinality == Cardinality::Optional)
    {
        out.push_str("\nfn optional<T>(mut values: Vec<T>, name: &str) -> Result<Option<T>, String> {\n    if values.len() > 1 { return Err(format!(\"expected at most one value for {name}, got {}\", values.len())); }\n    Ok(values.pop())\n}\n");
    }
    out.push_str("\nfn map_node(tree: &Tree, id: usize) -> Result<Vec<Ast>, String> {\n    match tree.nodes[id].rule {\n");
    for (index, rule) in ir.rules.iter().enumerate() {
        if rule.mapping.is_some() {
            writeln!(out, "        {index} => map_rule_{index}(tree, id),").unwrap();
        }
    }
    out.push_str("        _ => map_nodes(tree, &tree.nodes[id].children),\n    }\n}\n");
    for (index, rule) in ir.rules.iter().enumerate() {
        if let Some(mapping) = &rule.mapping {
            writeln!(
                out,
                "\n#[inline(never)]\nfn map_rule_{index}(tree: &Tree, id: usize) -> Result<Vec<Ast>, String> {{\n    let node = &tree.nodes[id];\n    Ok(vec![Ast::r#{} {{\n        span: node.span,",
                mapping.name
            )
            .unwrap();
            for field in &mapping.fields {
                writeln!(out, "        r#{}: {{\n            let mut values = Vec::new();\n            for capture in node.captures.iter().filter(|c| c.name == {}) {{", field.name, quote(&field.name)).unwrap();
                out.push_str(match field.kind {
                    Kind::Node => "                values.extend(map_nodes(tree, &capture.nodes)?);\n",
                    Kind::Value => "                values.extend(map_values(tree, &capture.nodes)?);\n",
                    Kind::Text => "                values.push(unlaxer_runtime::java_capture_text(tree.text(capture.span)).to_owned());\n",
                });
                writeln!(
                    out,
                    "            }}\n            {}\n        }},",
                    mapped_value(field)
                )
                .unwrap();
            }
            out.push_str("    }])\n}\n");
        }
    }
    out
}

fn evaluator(ir: &GrammarIr) -> String {
    let mut out = String::from(HEADER);
    if has_values(ir) {
        out.push_str("use super::ast::AstValue;\n");
    }
    out.push_str("use super::ast::Ast;\nuse unlaxer_runtime::Span;\n\n#[allow(non_snake_case)]\npub trait Semantics {\n    type Output;\n");
    for mapping in mappings(ir) {
        write!(out, "    fn {}(&mut self", method_name(&mapping.name)).unwrap();
        for field in &mapping.fields {
            write!(out, ", r#{}: {}", field.name, field_type(field, true)).unwrap();
        }
        out.push_str(", span: Span) -> Self::Output;\n");
    }
    out.push_str("}\n\n#[allow(non_snake_case)]\npub fn evaluate<S: Semantics>(node: &Ast, semantics: &mut S) -> S::Output {\n    match node {\n");
    for mapping in mappings(ir) {
        let mut args: Vec<_> = mapping
            .fields
            .iter()
            .map(|f| {
                format!(
                    "r#{}{}",
                    f.name,
                    if f.cardinality == Cardinality::Optional {
                        if f.kind == Kind::Value {
                            ".as_ref()"
                        } else {
                            ".as_deref()"
                        }
                    } else {
                        ""
                    }
                )
            })
            .collect();
        args.push("*span".into());
        writeln!(
            out,
            "        {} => semantics.{}({}),",
            pattern(mapping, "Ast"),
            method_name(&mapping.name),
            args.join(", ")
        )
        .unwrap();
    }
    out.push_str("    }\n}\n");
    out
}

fn pattern(mapping: &Mapping, ty: &str) -> String {
    let mut out = format!("{ty}::r#{} {{ span", mapping.name);
    for field in &mapping.fields {
        write!(out, ", r#{}", field.name).unwrap();
    }
    out.push_str(" }");
    out
}

fn field_type(field: &Field, borrowed: bool) -> String {
    let one = match (field.kind, borrowed) {
        (Kind::Node, true) => "&Ast",
        (Kind::Node, false) => "Box<Ast>",
        (Kind::Text, true) => "&str",
        (Kind::Text, false) => "String",
        (Kind::Value, true) => "&AstValue",
        (Kind::Value, false) => "AstValue",
    };
    match field.cardinality {
        Cardinality::One => one.into(),
        Cardinality::Optional => format!("Option<{one}>"),
        Cardinality::Many => {
            let element = match field.kind {
                Kind::Node => "Ast",
                Kind::Text => "String",
                Kind::Value => "AstValue",
            };
            if borrowed {
                format!("&[{element}]")
            } else {
                format!("Vec<{element}>")
            }
        }
    }
}

fn mapped_value(field: &Field) -> String {
    let name = quote(&field.name);
    match field.cardinality {
        Cardinality::One if field.kind == Kind::Node => {
            format!("Box::new(required(values, {name})?)")
        }
        Cardinality::One => format!("required(values, {name})?"),
        Cardinality::Optional => format!(
            "optional(values, {name})?{}",
            if field.kind == Kind::Node {
                ".map(Box::new)"
            } else {
                ""
            }
        ),
        Cardinality::Many => "values".into(),
    }
}

fn field_json(field: &Field) -> String {
    let name = format!("r#{}", field.name);
    let value = if field.kind != Kind::Text {
        "value.canonical_json()"
    } else {
        "json_string(value)"
    };
    match field.cardinality {
        Cardinality::One if field.kind != Kind::Text => format!("{name}.canonical_json()"),
        Cardinality::One => format!("json_string({name})"),
        Cardinality::Optional => format!("{name}.as_ref().map_or_else(|| \"null\".to_owned(), |value| {value})"),
        Cardinality::Many => format!("format!(\"[{{}}]\", {name}.iter().map(|value| {value}).collect::<Vec<_>>().join(\",\"))"),
    }
}

fn method_name(name: &str) -> String {
    let mut result = String::from("eval_");
    let mut previous = None;
    for c in name.chars() {
        if c.is_ascii_uppercase()
            && previous.is_some_and(|p: char| p.is_ascii_lowercase() || p.is_ascii_digit())
        {
            result.push('_');
        }
        result.push(c.to_ascii_lowercase());
        previous = Some(c);
    }
    result
}

fn quote(value: &str) -> String {
    let mut out = String::from("\"");
    for c in value.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if c < ' ' || c == '\u{7f}' => write!(out, "\\u{{{:x}}}", u32::from(c)).unwrap(),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}
