#!/usr/bin/env python3
"""Generate both host tables from the pinned Unicode property data; --check never writes."""
import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / 'spec-corpus/xid-identifier/unicode-17.0.0.txt'


def ranges(property_name):
    result = []
    for line in SOURCE.read_text().splitlines():
        if line.startswith('#'):
            continue
        value, property_value = line.split(';')
        if property_value != property_name:
            continue
        limits = value.split('..')
        start, end = int(limits[0], 16), int(limits[-1], 16)
        if result and result[-1][1] + 1 == start:
            result[-1] = result[-1][0], end
        else:
            result.append((start, end))
    return result


def generate():
    start, continuing = ranges('XID_Start'), ranges('XID_Continue')
    notice = 'Generated by scripts/generate-xid-tables.py from Unicode 17.0.0.\n// Copyright (c) 2025 Unicode, Inc. See spec-corpus/xid-identifier/UNICODE-LICENSE.txt.'
    java = '// ' + notice + '''
package org.unlaxer.dsl.runtime;

/** Fixed Unicode XID properties, independent of the running JDK's Unicode version. */
final class UnicodeXid {
    private UnicodeXid() {}

    static int identifierEnd(String source, int position) {
        if (position < 0 || position >= source.length()) { return -1; }
        int codePoint = source.codePointAt(position);
        if (false == contains(START, codePoint)) { return -1; }
        int end = position + Character.charCount(codePoint);
        while (end < source.length()) {
            codePoint = source.codePointAt(end);
            if (false == contains(CONTINUE, codePoint)) { break; }
            end += Character.charCount(codePoint);
        }
        return end;
    }

    private static boolean contains(int[] ranges, int codePoint) {
        int low = 0;
        int high = ranges.length / 2;
        while (low < high) {
            int middle = (low + high) >>> 1;
            if (codePoint < ranges[middle * 2]) { high = middle; }
            else if (codePoint > ranges[middle * 2 + 1]) { low = middle + 1; }
            else { return true; }
        }
        return false;
    }
'''
    rust = '// ' + notice + '''

pub(crate) fn identifier_end(source: &str, position: usize) -> Option<usize> {
    let mut characters = source.get(position..)?.char_indices();
    let (_, first) = characters.next()?;
    if !contains(START, first as u32) {
        return None;
    }
    let mut end = position + first.len_utf8();
    for (offset, character) in characters {
        if !contains(CONTINUE, character as u32) {
            break;
        }
        end = position + offset + character.len_utf8();
    }
    Some(end)
}

fn contains(ranges: &[(u32, u32)], codepoint: u32) -> bool {
    ranges.binary_search_by(|&(start, end)| {
        if codepoint < start { std::cmp::Ordering::Greater }
        else if codepoint > end { std::cmp::Ordering::Less }
        else { std::cmp::Ordering::Equal }
    }).is_ok()
}
'''
    for name, values in [('START', start), ('CONTINUE', continuing)]:
        java += '\n    private static final int[] ' + name + ' = {\n'
        for index in range(0, len(values), 4):
            java += '        ' + ', '.join(f'0x{a:x}, 0x{b:x}' for a, b in values[index:index+4]) + ',\n'
        java += '    };\n'
        rust += '\nconst ' + name + ': &[(u32, u32)] = &[\n'
        for a, b in values:
            rust += f'    (0x{a:x}, 0x{b:x}),\n'
        rust += '];\n'
    java += '}\n'
    # Match rustfmt's default wrapping without relying on network or a toolchain.
    rust = rust.replace('ranges.binary_search_by(|&(start, end)| {', 'ranges\n        .binary_search_by(|&(start, end)| {').replace('        if codepoint < start { std::cmp::Ordering::Greater }\n        else if codepoint > end { std::cmp::Ordering::Less }\n        else { std::cmp::Ordering::Equal }\n    }).is_ok()', '''            if codepoint < start {
                std::cmp::Ordering::Greater
            } else if codepoint > end {
                std::cmp::Ordering::Less
            } else {
                std::cmp::Ordering::Equal
            }
        })
        .is_ok()''')
    return {
        ROOT / 'unlaxer-dsl/src/main/java/org/unlaxer/dsl/runtime/UnicodeXid.java': java,
        ROOT / 'rust/unlaxer-runtime/src/unicode_xid.rs': rust,
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    options = parser.parse_args()
    for path, source in generate().items():
        if options.check:
            if not path.exists() or path.read_text() != source:
                raise SystemExit(f'Unicode XID table drift: {path.relative_to(ROOT)}')
        else:
            path.write_text(source)


if __name__ == '__main__':
    main()
