use std::ffi::OsString;
use std::fs::{self, OpenOptions};
use std::io::{self, Write};
use std::path::{Path, PathBuf};
use std::process::ExitCode;
use unlaxer_codegen::GeneratedFile;

const HELP: &str =
    "Usage: unlaxer generate [--target rust] --grammar <file.ubnf> --output <module-directory> [--check]\n       unlaxer playground --grammar <file.ubnf> --output <new-directory> [--check]\n       unlaxer check --target rust --grammar <file.ubnf> [--format json]\n       unlaxer impact --target rust --before <old.ubnf> --after <new.ubnf> [--format json]";
const CHECK_HELP: &str = "Usage: unlaxer check --target rust --grammar <file.ubnf> [--format json]";
const IMPACT_HELP: &str =
    "Usage: unlaxer impact --target rust --before <old.ubnf> --after <new.ubnf> [--format json]";
const HEADER: &str = "// Generated by unlaxer RustBackend.";
const PLAYGROUND_HELP: &str =
    "Usage: unlaxer playground --grammar <file.ubnf> --output <new-directory> [--check]";

fn main() -> ExitCode {
    let args: Vec<_> = std::env::args_os().skip(1).collect();
    let result = if args.first().and_then(|s| s.to_str()) == Some("deps") {
        run_deps(args)
    } else if args.first().and_then(|s| s.to_str()) == Some("playground") {
        run_playground(args).map(|message| (0, message))
    } else if args.first().and_then(|s| s.to_str()) == Some("check") {
        run_check(args)
    } else if args.first().and_then(|s| s.to_str()) == Some("impact") {
        run_impact(args)
    } else {
        run(args).map(|message| (0, message))
    };
    match result {
        Ok((code, message)) => {
            println!("{message}");
            ExitCode::from(code)
        }
        Err((code, message)) => {
            eprintln!("{message}");
            ExitCode::from(code)
        }
    }
}

fn run_deps(args: Vec<OsString>) -> Result<(u8, String), (u8, String)> {
    let help = "Usage: unlaxer deps resolve --manifest <ubnf.json>";
    if args == [OsString::from("deps"), OsString::from("--help")] {
        return Ok((0, help.into()));
    }
    if args.len() != 4 || args[1] != "resolve" || args[2] != "--manifest" || args[3].is_empty() {
        return Err((2, help.into()));
    }
    unlaxer_generator::packages::resolve(&PathBuf::from(&args[3]))
        .map(|lock| (0, lock.to_string()))
        .map_err(|message| (3, message))
}

fn run_impact(args: Vec<OsString>) -> Result<(u8, String), (u8, String)> {
    if args == [OsString::from("impact"), OsString::from("--help")] {
        return Ok((0, IMPACT_HELP.into()));
    }
    let (mut before, mut after, mut target, mut format) = (None, None, false, false);
    let mut cursor = 1;
    while cursor < args.len() {
        let option = args[cursor]
            .to_str()
            .ok_or((2, "invalid option encoding".into()))?;
        if cursor + 1 == args.len() || args[cursor + 1].to_string_lossy().starts_with("--") {
            return Err((2, format!("incomplete option {option}\n{IMPACT_HELP}")));
        }
        let value = &args[cursor + 1];
        match option {
            "--before" if before.is_none() && !value.is_empty() => {
                before = Some(PathBuf::from(value))
            }
            "--after" if after.is_none() && !value.is_empty() => after = Some(PathBuf::from(value)),
            "--target" if !target && value == "rust" => target = true,
            "--format" if !format && value == "json" => format = true,
            _ => {
                return Err((
                    2,
                    format!("invalid, duplicate or unknown option {option}\n{IMPACT_HELP}"),
                ))
            }
        }
        cursor += 2;
    }
    if !target {
        return Err((2, IMPACT_HELP.into()));
    }
    let before = before.ok_or((2, IMPACT_HELP.into()))?;
    let after = after.ok_or((2, IMPACT_HELP.into()))?;
    let before_source = fs::read_to_string(before).map_err(io_error)?;
    let after_source = fs::read_to_string(after).map_err(io_error)?;
    let report = unlaxer_generator::impact::compare(&before_source, &after_source);
    Ok((if report.ok { 0 } else { 3 }, report.to_json()))
}

fn run_check(args: Vec<OsString>) -> Result<(u8, String), (u8, String)> {
    if args == [OsString::from("check"), OsString::from("--help")] {
        return Ok((0, CHECK_HELP.into()));
    }
    let mut grammar = None;
    let mut target = false;
    let mut format = false;
    let mut cursor = 1;
    while cursor < args.len() {
        let option = args[cursor]
            .to_str()
            .ok_or((2, "invalid option encoding".into()))?;
        if cursor + 1 == args.len() || args[cursor + 1].to_string_lossy().starts_with("--") {
            return Err((2, format!("incomplete option {option}\n{CHECK_HELP}")));
        }
        let value = &args[cursor + 1];
        match option {
            "--grammar" if grammar.is_none() && !value.is_empty() => {
                grammar = Some(PathBuf::from(value))
            }
            "--target" if !target && value == "rust" => target = true,
            "--format" if !format && value == "json" => format = true,
            _ => {
                return Err((
                    2,
                    format!("invalid, duplicate or unknown option {option}\n{CHECK_HELP}"),
                ))
            }
        }
        cursor += 2;
    }
    if !target {
        return Err((2, CHECK_HELP.into()));
    }
    let grammar = grammar.ok_or((2, CHECK_HELP.into()))?;
    let source = fs::read_to_string(&grammar).map_err(io_error)?;
    let report = if unlaxer_ubnf::parse(&source).is_err() {
        unlaxer_generator::portability::check(&source)
    } else {
        unlaxer_generator::portability::check_file(&grammar)
    };
    Ok((if report.portable { 0 } else { 3 }, report.to_json()))
}

fn run(args: Vec<OsString>) -> Result<String, (u8, String)> {
    if args == [OsString::from("--help")]
        || args == [OsString::from("generate"), OsString::from("--help")]
    {
        return Ok(HELP.into());
    }
    if args.first().and_then(|s| s.to_str()) != Some("generate") {
        return Err((2, HELP.into()));
    }
    let mut grammar = None;
    let mut output = None;
    let mut check = false;
    let mut explicit_target = false;
    let mut cursor = 1;
    while cursor < args.len() {
        let option = args[cursor]
            .to_str()
            .ok_or((2, "invalid option encoding".into()))?;
        if option == "--check" {
            if check {
                return Err((2, "duplicate --check".into()));
            }
            check = true;
            cursor += 1;
            continue;
        }
        if !matches!(option, "--grammar" | "--output" | "--target")
            || cursor + 1 == args.len()
            || args[cursor + 1].to_string_lossy().starts_with("--")
        {
            return Err((2, format!("unknown or incomplete option {option}\n{HELP}")));
        }
        if option == "--target" {
            if explicit_target || args[cursor + 1] != "rust" {
                return Err((2, "target must be rust and specified at most once".into()));
            }
            explicit_target = true;
            cursor += 2;
            continue;
        }
        let target = if option == "--grammar" {
            &mut grammar
        } else {
            &mut output
        };
        if target.replace(PathBuf::from(&args[cursor + 1])).is_some() {
            return Err((2, format!("duplicate {option}")));
        }
        cursor += 2;
    }
    let grammar = grammar.ok_or((2, HELP.into()))?;
    let output = output.ok_or((2, HELP.into()))?;
    if grammar.as_os_str().is_empty() || output.as_os_str().is_empty() {
        return Err((2, "grammar and output paths must not be empty".into()));
    }
    // Keep I/O exit status separate from grammar/link errors for the entry file.
    fs::read_to_string(&grammar).map_err(io_error)?;
    let files = unlaxer_generator::generate_file(&grammar).map_err(|message| (3, message))?;
    write_artifacts(&output, &files, check).map_err(io_error)?;
    Ok(format!(
        "{} {} Rust module files in {}",
        if check { "Verified" } else { "Generated" },
        files.len(),
        output.display()
    ))
}

fn io_error(error: io::Error) -> (u8, String) {
    (4, error.to_string())
}

fn run_playground(args: Vec<OsString>) -> Result<String, (u8, String)> {
    if args == [OsString::from("playground"), OsString::from("--help")] {
        return Ok(PLAYGROUND_HELP.into());
    }
    let (mut grammar, mut output, mut check) = (None, None, false);
    let mut cursor = 1;
    while cursor < args.len() {
        let option = args[cursor].to_str().ok_or((2, PLAYGROUND_HELP.into()))?;
        if option == "--check" && !check {
            check = true;
            cursor += 1;
            continue;
        }
        if !matches!(option, "--grammar" | "--output")
            || cursor + 1 == args.len()
            || args[cursor + 1].is_empty()
            || args[cursor + 1].to_string_lossy().starts_with("--")
        {
            return Err((2, PLAYGROUND_HELP.into()));
        }
        let target = if option == "--grammar" {
            &mut grammar
        } else {
            &mut output
        };
        if target.replace(PathBuf::from(&args[cursor + 1])).is_some() {
            return Err((2, format!("duplicate {option}")));
        }
        cursor += 2;
    }
    let grammar = grammar.ok_or((2, PLAYGROUND_HELP.into()))?;
    let output = output.ok_or((2, PLAYGROUND_HELP.into()))?;
    fs::read_to_string(&grammar).map_err(io_error)?;
    let files =
        unlaxer_generator::playground::generate_file(&grammar).map_err(|message| (3, message))?;
    write_playground(&output, &files, check).map_err(io_error)?;
    Ok(format!("{} {} playground files in {}\nNext: cd <output>, npm run build, npm start. Rust wasm32 target and Node 20+ are required.",
        if check { "Verified" } else { "Generated" }, files.len(), output.display()))
}

fn write_playground(output: &Path, files: &[GeneratedFile], check: bool) -> io::Result<()> {
    let output = std::path::absolute(output)?;
    reject_symlink_ancestors(&output)?;
    if check {
        for file in files {
            let destination = output.join(&file.relative_path);
            reject_symlink_ancestors(&destination)?;
            if fs::read_to_string(&destination)? != file.content {
                return Err(invalid(format!(
                    "generated file differs: {}",
                    destination.display()
                )));
            }
        }
        return Ok(());
    }
    if output.exists() {
        return Err(invalid(format!(
            "output already exists; choose a new directory: {}",
            output.display()
        )));
    }
    let parent = output
        .parent()
        .ok_or_else(|| invalid("output needs a parent"))?;
    fs::create_dir_all(parent)?;
    let mut staging = None;
    for attempt in 0..100 {
        let candidate = parent.join(format!(".ubnf-playground-{}-{attempt}", std::process::id()));
        match fs::create_dir(&candidate) {
            Ok(()) => {
                staging = Some(candidate);
                break;
            }
            Err(error) if error.kind() == io::ErrorKind::AlreadyExists => continue,
            Err(error) => return Err(error),
        }
    }
    let staging = staging.ok_or_else(|| invalid("cannot allocate playground staging directory"))?;
    let result = (|| {
        for file in files {
            let destination = staging.join(&file.relative_path);
            fs::create_dir_all(destination.parent().unwrap())?;
            let mut handle = OpenOptions::new()
                .write(true)
                .create_new(true)
                .open(destination)?;
            handle.write_all(file.content.as_bytes())?;
        }
        if output.exists() {
            return Err(invalid("output was created during generation"));
        }
        fs::rename(&staging, &output)
    })();
    result.map_err(|error| {
        invalid(format!(
            "Generation failed; partial staging retained at {}: {error}",
            staging.display()
        ))
    })
}
fn invalid(message: impl Into<String>) -> io::Error {
    io::Error::new(io::ErrorKind::InvalidInput, message.into())
}

fn reject_symlink_ancestors(path: &Path) -> io::Result<()> {
    for ancestor in path.ancestors().filter(|p| !p.as_os_str().is_empty()) {
        // A trailing slash or /. makes stat follow the link on Unix. Remove only
        // lexical dot/slash decoration; do not resolve '..' through a symlink.
        let normalized: PathBuf = ancestor.components().collect();
        match fs::symlink_metadata(&normalized) {
            Ok(metadata) if metadata.file_type().is_symlink() => {
                return Err(invalid(format!(
                    "refusing symbolic link {}",
                    ancestor.display()
                )))
            }
            Ok(_) => {}
            Err(error) if error.kind() == io::ErrorKind::NotFound => {}
            Err(error) => return Err(error),
        }
    }
    Ok(())
}

fn write_artifacts(output: &Path, files: &[GeneratedFile], check: bool) -> io::Result<()> {
    reject_symlink_ancestors(output)?;
    // Preflight every artifact. Unsupported input and handwritten files cause no writes.
    for file in files {
        let destination = output.join(&file.relative_path);
        match fs::symlink_metadata(&destination) {
            Ok(metadata) => {
                if metadata.file_type().is_symlink() || !metadata.is_file() {
                    return Err(invalid(format!(
                        "refusing non-regular file {}",
                        destination.display()
                    )));
                }
                let previous = fs::read_to_string(&destination)?;
                if check {
                    if previous != file.content {
                        return Err(invalid(format!(
                            "generated file differs: {}",
                            destination.display()
                        )));
                    }
                } else if !previous.starts_with(HEADER) {
                    return Err(invalid(format!(
                        "refusing to overwrite handwritten file {}",
                        destination.display()
                    )));
                }
            }
            Err(error) if error.kind() == io::ErrorKind::NotFound && !check => {}
            Err(error) => return Err(error),
        }
    }
    if check {
        return Ok(());
    }
    fs::create_dir_all(output)?;
    // Per-file replacement avoids truncation on a failed write and does not follow a
    // destination symlink introduced after preflight. This is not a directory transaction.
    for (i, file) in files.iter().enumerate() {
        let temporary = output.join(format!(".unlaxer-{}-{i}.tmp", std::process::id()));
        let mut handle = OpenOptions::new()
            .write(true)
            .create_new(true)
            .open(&temporary)?;
        let result = (|| {
            handle.write_all(file.content.as_bytes())?;
            handle.sync_all()?;
            drop(handle);
            fs::rename(&temporary, output.join(&file.relative_path))
        })();
        if result.is_err() {
            let _ = fs::remove_file(&temporary);
        }
        result?;
    }
    Ok(())
}
