use std::ffi::OsString;
use std::fs::{self, OpenOptions};
use std::io::{self, Write};
use std::path::{Path, PathBuf};
use std::process::ExitCode;
use unlaxer_codegen::GeneratedFile;

const HELP: &str =
    "Usage: unlaxer generate [--target rust] --grammar <file.ubnf> --output <module-directory> [--check]";
const HEADER: &str = "// Generated by unlaxer RustBackend.";

fn main() -> ExitCode {
    match run(std::env::args_os().skip(1).collect()) {
        Ok(message) => {
            println!("{message}");
            ExitCode::SUCCESS
        }
        Err((code, message)) => {
            eprintln!("{message}");
            ExitCode::from(code)
        }
    }
}

fn run(args: Vec<OsString>) -> Result<String, (u8, String)> {
    if args == [OsString::from("--help")]
        || args == [OsString::from("generate"), OsString::from("--help")]
    {
        return Ok(HELP.into());
    }
    if args.first().and_then(|s| s.to_str()) != Some("generate") {
        return Err((2, HELP.into()));
    }
    let mut grammar = None;
    let mut output = None;
    let mut check = false;
    let mut explicit_target = false;
    let mut cursor = 1;
    while cursor < args.len() {
        let option = args[cursor]
            .to_str()
            .ok_or((2, "invalid option encoding".into()))?;
        if option == "--check" {
            if check {
                return Err((2, "duplicate --check".into()));
            }
            check = true;
            cursor += 1;
            continue;
        }
        if !matches!(option, "--grammar" | "--output" | "--target")
            || cursor + 1 == args.len()
            || args[cursor + 1].to_string_lossy().starts_with("--")
        {
            return Err((2, format!("unknown or incomplete option {option}\n{HELP}")));
        }
        if option == "--target" {
            if explicit_target || args[cursor + 1] != "rust" {
                return Err((2, "target must be rust and specified at most once".into()));
            }
            explicit_target = true;
            cursor += 2;
            continue;
        }
        let target = if option == "--grammar" {
            &mut grammar
        } else {
            &mut output
        };
        if target.replace(PathBuf::from(&args[cursor + 1])).is_some() {
            return Err((2, format!("duplicate {option}")));
        }
        cursor += 2;
    }
    let grammar = grammar.ok_or((2, HELP.into()))?;
    let output = output.ok_or((2, HELP.into()))?;
    if grammar.as_os_str().is_empty() || output.as_os_str().is_empty() {
        return Err((2, "grammar and output paths must not be empty".into()));
    }
    let source = fs::read_to_string(&grammar).map_err(io_error)?;
    let files = unlaxer_generator::generate(&source).map_err(|message| (3, message))?;
    write_artifacts(&output, &files, check).map_err(io_error)?;
    Ok(format!(
        "{} {} Rust module files in {}",
        if check { "Verified" } else { "Generated" },
        files.len(),
        output.display()
    ))
}

fn io_error(error: io::Error) -> (u8, String) {
    (4, error.to_string())
}
fn invalid(message: impl Into<String>) -> io::Error {
    io::Error::new(io::ErrorKind::InvalidInput, message.into())
}

fn reject_symlink_ancestors(path: &Path) -> io::Result<()> {
    for ancestor in path.ancestors().filter(|p| !p.as_os_str().is_empty()) {
        // A trailing slash or /. makes stat follow the link on Unix. Remove only
        // lexical dot/slash decoration; do not resolve '..' through a symlink.
        let normalized: PathBuf = ancestor.components().collect();
        match fs::symlink_metadata(&normalized) {
            Ok(metadata) if metadata.file_type().is_symlink() => {
                return Err(invalid(format!(
                    "refusing symbolic link {}",
                    ancestor.display()
                )))
            }
            Ok(_) => {}
            Err(error) if error.kind() == io::ErrorKind::NotFound => {}
            Err(error) => return Err(error),
        }
    }
    Ok(())
}

fn write_artifacts(output: &Path, files: &[GeneratedFile], check: bool) -> io::Result<()> {
    reject_symlink_ancestors(output)?;
    // Preflight every artifact. Unsupported input and handwritten files cause no writes.
    for file in files {
        let destination = output.join(&file.relative_path);
        match fs::symlink_metadata(&destination) {
            Ok(metadata) => {
                if metadata.file_type().is_symlink() || !metadata.is_file() {
                    return Err(invalid(format!(
                        "refusing non-regular file {}",
                        destination.display()
                    )));
                }
                let previous = fs::read_to_string(&destination)?;
                if check {
                    if previous != file.content {
                        return Err(invalid(format!(
                            "generated file differs: {}",
                            destination.display()
                        )));
                    }
                } else if !previous.starts_with(HEADER) {
                    return Err(invalid(format!(
                        "refusing to overwrite handwritten file {}",
                        destination.display()
                    )));
                }
            }
            Err(error) if error.kind() == io::ErrorKind::NotFound && !check => {}
            Err(error) => return Err(error),
        }
    }
    if check {
        return Ok(());
    }
    fs::create_dir_all(output)?;
    // Per-file replacement avoids truncation on a failed write and does not follow a
    // destination symlink introduced after preflight. This is not a directory transaction.
    for (i, file) in files.iter().enumerate() {
        let temporary = output.join(format!(".unlaxer-{}-{i}.tmp", std::process::id()));
        let mut handle = OpenOptions::new()
            .write(true)
            .create_new(true)
            .open(&temporary)?;
        let result = (|| {
            handle.write_all(file.content.as_bytes())?;
            handle.sync_all()?;
            drop(handle);
            fs::rename(&temporary, output.join(&file.relative_path))
        })();
        if result.is_err() {
            let _ = fs::remove_file(&temporary);
        }
        result?;
    }
    Ok(())
}
