package org.unlaxer.dsl.codegen.rust;

import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;
import org.unlaxer.dsl.bootstrap.UBNFAST.GrammarDecl;
import org.unlaxer.dsl.codegen.rust.GrammarIR.*;

/**
 * Emits a Rust module, not a Cargo manifest or handwritten semantics.
 * The frontend must run the common GrammarValidator first, as for the Java generators.
 * RustGrammarLowering additionally checks Rust-specific support and structural constraints.
 */
public final class RustBackend {
    public record GeneratedFile(String relativePath, String content) {}
    private static final String HEADER = "// Generated by unlaxer RustBackend. Regenerate; do not edit.\n";

    public List<GeneratedFile> generate(GrammarDecl grammar) {
        GrammarIR ir = RustGrammarLowering.lower(grammar);
        return List.of(
            new GeneratedFile("mod.rs", HEADER + """
                pub mod ast;
                pub mod parser;
                pub mod mapper;
                pub mod evaluator;
                """),
            new GeneratedFile("ast.rs", ast(ir)),
            new GeneratedFile("parser.rs", parser(ir)),
            new GeneratedFile("mapper.rs", mapper(ir)),
            new GeneratedFile("evaluator.rs", evaluator(ir)));
    }

    private String ast(GrammarIR ir) {
        StringBuilder out = new StringBuilder(HEADER);
        out.append("use unlaxer_runtime::{Span, json_string};\n\n");
        if (hasValues(ir)) out.append("""
            #[derive(Debug, Clone, PartialEq)]
            pub enum AstValue {
                Text { text: String, span: Span },
                Node(Box<Ast>),
            }

            impl AstValue {
                pub fn span(&self) -> Span {
                    match self {
                        Self::Text { span, .. } => *span,
                        Self::Node(node) => node.span(),
                    }
                }

                pub fn canonical_json(&self) -> String {
                    match self {
                        Self::Text { text, .. } => json_string(text),
                        Self::Node(node) => node.canonical_json(),
                    }
                }
            }

            """);
        out.append("#[allow(non_snake_case, non_camel_case_types)]\n#[derive(Debug, Clone, PartialEq)]\npub enum Ast {\n");
        for (Mapping mapping : ir.mappings()) {
            out.append("    r#").append(mapping.name()).append(" { span: Span");
            for (Field field : mapping.fields()) out.append(", r#").append(field.name()).append(": ")
                .append(fieldType(field, false));
            out.append(" },\n");
        }
        out.append("}\n\n#[allow(non_snake_case)]\nimpl Ast {\n    pub fn span(&self) -> Span {\n        match self {\n");
        for (Mapping mapping : ir.mappings()) {
            out.append("            Self::r#").append(mapping.name()).append(" { span, .. } => *span,\n");
        }
        out.append("        }\n    }\n\n    pub fn canonical_json(&self) -> String {\n        match self {\n");
        for (Mapping mapping : ir.mappings()) {
            out.append("            ").append(pattern(mapping, "Self")).append(" => {\n");
            out.append("                let fields: Vec<String> = vec![\n");
            for (Field field : mapping.fields()) {
                out.append("                    format!(\"{}:{}\", json_string(").append(quote(field.name())).append("), ")
                    .append(fieldJson(field)).append("),\n");
            }
            out.append("                ];\n                format!(\"{{\\\"type\\\":{},\\\"span\\\":[{},{}],\\\"fields\\\":{{{}}}}}\", json_string(")
                .append(quote(mapping.name())).append("), span.start, span.end, fields.join(\",\"))\n            },\n");
        }
        out.append("        }\n    }\n}\n");
        return out.toString();
    }

    private String parser(GrammarIR ir) {
        StringBuilder out = new StringBuilder(HEADER);
        out.append("""
            use std::sync::OnceLock;
            #[cfg(test)]
            use std::sync::atomic::{AtomicUsize, Ordering};
            use unlaxer_runtime::{Expr, Rule, SharedGrammar, Tree, ParseError, ParseDiagnostic, ParseContext, ParseResult, Parser};

            #[cfg(test)]
            static GRAMMAR_INITIALIZATIONS: AtomicUsize = AtomicUsize::new(0);

            pub struct GeneratedParser;

            impl Parser for GeneratedParser {
                fn parse(&self, context: &mut ParseContext<'_>) -> ParseResult {
                    parse_context(context)
                }
            }

            pub fn parse_tree(source: &str) -> Result<Tree, ParseError> {
                parse_tree_detailed(source).map_err(|diagnostic| diagnostic.farthest)
            }

            /// Compatibility snapshot of the generated rules. Parsing uses `grammar()` and does not clone them.
            pub fn rules() -> Vec<Rule> {
                grammar().iter().cloned().collect()
            }

            /// Immutable grammar graph, initialized once and shared by every parse.
            pub fn grammar() -> &'static SharedGrammar {
                static GRAMMAR: OnceLock<SharedGrammar> = OnceLock::new();
                GRAMMAR.get_or_init(|| {
                    #[cfg(test)]
                    GRAMMAR_INITIALIZATIONS.fetch_add(1, Ordering::Relaxed);
                    vec![
            """);
        for (Rule rule : ir.rules()) out.append("            Rule { name: ").append(quote(rule.name()))
            .append(", expression: ").append(expression(rule.body())).append(" },\n");
        out.append("        ].into()\n    })\n}\n\n/// Test-only evidence for the process-wide `OnceLock` construction contract.\n#[cfg(test)]\n#[doc(hidden)]\npub fn grammar_initialization_count() -> usize {\n    GRAMMAR_INITIALIZATIONS.load(Ordering::Relaxed)\n}\n\npub fn parse_context(context: &mut ParseContext<'_>) -> ParseResult {\n    context.parse_shared_grammar(grammar(), ")
            .append(ir.root()).append(", ").append(ir.javaWhitespace()).append(")\n}\n");
        out.append("\npub fn parse_tree_detailed(source: &str) -> Result<Tree, ParseDiagnostic> {\n    unlaxer_runtime::parse_detailed_shared(grammar(), ")
            .append(ir.root()).append(", ").append(ir.javaWhitespace()).append(", source)\n}\n");
        if (ir.rules().stream().anyMatch(r -> r.operator() != null)) {
            out.append("""

                /// Descriptive metadata; parsing precedence follows the grammar's rule graph.
                #[derive(Debug, Clone, Copy, PartialEq, Eq)]
                pub enum Associativity { %s }
                #[derive(Debug, Clone, Copy, PartialEq, Eq)]
                pub struct OperatorSpec {
                    pub rule: &'static str,
                    pub precedence: i32,
                    pub associativity: Associativity,
                }
                pub const OPERATORS: &[OperatorSpec] = &[
                """.formatted(ir.rules().stream().anyMatch(r -> r.operator() != null
                    && r.operator().associativity() == Associativity.RIGHT) ? "Left, Right, None" : "Left, None"));
            ir.rules().stream().filter(r -> r.operator() != null)
                .sorted(java.util.Comparator.comparingInt((Rule r) -> r.operator().precedence()).thenComparing(Rule::name))
                .forEach(rule -> out.append("    OperatorSpec { rule: ").append(quote(rule.name()))
                    .append(", precedence: ").append(rule.operator().precedence()).append(", associativity: Associativity::")
                    .append(switch (rule.operator().associativity()) {
                        case LEFT -> "Left";
                        case RIGHT -> "Right";
                        case NONE -> "None";
                    }).append(" },\n"));
            out.append("];\n");
        }
        if (ir.rules().stream().anyMatch(r -> r.catalog() != null)) {
            out.append("""

                /// Catalog targets retained for future context-aware tooling.
                #[derive(Debug, Clone, Copy, PartialEq, Eq)]
                pub struct CatalogSpec {
                    pub rule: &'static str,
                    pub context: &'static str,
                    pub captures: &'static [&'static str],
                }
                pub const CATALOGS: &[CatalogSpec] = &[
                """);
            ir.rules().stream().filter(rule -> rule.catalog() != null).forEach(rule -> {
                String captures = rule.catalog().captures().stream().map(RustBackend::quote)
                    .collect(java.util.stream.Collectors.joining(", "));
                out.append("    CatalogSpec { rule: ").append(quote(rule.name()))
                    .append(", context: ").append(quote(rule.catalog().context()))
                    .append(", captures: &[").append(captures).append("] },\n");
            });
            out.append("];\n");
        }
        return out.toString();
    }

    private String expression(Expression expression) {
        return switch (expression) {
            case RuleEffects scope -> expression(scope.child()) + ".rule_effects(" + effects(scope.effects()) + ")";
            case Literal literal -> "Expr::Literal(" + quote(literal.text()) + ")";
            case NumberToken ignored -> "Expr::Number";
            case IdentifierToken ignored -> "Expr::Identifier";
            case QuotedToken quoted -> "Expr::Quoted('\\u{" + Integer.toHexString(quoted.quote()) + "}')";
            case CodeStartToken ignored -> "Expr::CodeStart";
            case CodeEndToken ignored -> "Expr::CodeEnd";
            case AnyToken ignored -> "Expr::Any";
            case EofToken ignored -> "Expr::Eof";
            case EmptyToken ignored -> "Expr::JavaEmpty";
            case CharRangeToken range -> "Expr::CharRange('\\u{" + Integer.toHexString(range.min())
                + "}', '\\u{" + Integer.toHexString(range.max()) + "}')";
            case ExceptToken except -> "Expr::Except(" + quote(except.excluded()) + ")";
            case UntilToken until -> "Expr::JavaUntil(" + quote(until.terminator()) + ")";
            case LookaheadToken lookahead -> "Expr::JavaLookahead { pattern: " + quote(lookahead.pattern())
                + ", positive: " + lookahead.positive() + " }";
            case Reference reference -> "Expr::Rule(" + reference.rule() + ")";
            case Sequence sequence -> "Expr::Sequence(vec![" + expressions(sequence.elements()) + "])";
            case Delimited delimited -> "Expr::Sequence(vec![" + expression(delimited.child()) + "])";
            case Choice choice -> "Expr::Choice(vec![" + expressions(choice.alternatives()) + "])";
            case Capture capture -> "Expr::Capture(" + quote(capture.name()) + ", Box::new(" + expression(capture.expression()) + "))";
            case TextValue text -> expression(text.child()) + ".text_value()";
            case ValueBoundary boundary -> expression(boundary.child()) + ".value_boundary()";
            case TriviaScope scope -> expression(scope.child()) + ".trivia_scope(" + scope.javaWhitespace() + ")";
            case OptionalExpr optional -> expression(optional.child()) + ".optional_java()";
            case Repeat repeat -> expression(repeat.child()) + ".repeat_java(" + repeat.min() + ", "
                + (repeat.max() == null ? "None" : "Some(" + repeat.max() + ")") + ")";
            case Separated separated -> expression(separated.child()) + ".separated_by(" + expression(separated.separator()) + ")";
        };
    }

    private String effects(Effects effects) {
        String scope = effects.scopeMode() == null ? "None" : "Some(unlaxer_runtime::ScopeMode::"
            + (effects.scopeMode() == ScopeMode.LEXICAL ? "Lexical" : "Dynamic") + ")";
        Declaration decl = effects.declares();
        String declares = decl == null ? "None" : "Some(unlaxer_runtime::Declaration { symbol_capture: "
            + quote(decl.symbolCapture()) + ", description: " + optionText(decl.description()) + " })";
        return "unlaxer_runtime::RuleEffects { scope_mode: " + scope + ", declares: " + declares
            + ", backref: " + optionText(effects.backref()) + " }";
    }

    private String optionText(String value) {
        return value == null ? "None" : "Some(" + quote(value) + ")";
    }

    private String expressions(List<Expression> expressions) {
        return expressions.stream().map(this::expression).collect(Collectors.joining(", "));
    }

    private String mapper(GrammarIR ir) {
        StringBuilder out = new StringBuilder(HEADER);
        if (hasValues(ir)) out.append("use super::ast::AstValue;\n");
        out.append("use super::ast::Ast;\nuse unlaxer_runtime::Tree;\n\n");
        out.append("""
            pub fn map(tree: &Tree) -> Result<Ast, String> {
                required(map_node(tree, tree.root)?, "root")
            }

            fn required<T>(mut values: Vec<T>, name: &str) -> Result<T, String> {
                if values.len() != 1 { return Err(format!("expected one value for {name}, got {}", values.len())); }
                Ok(values.remove(0))
            }

            fn map_nodes(tree: &Tree, ids: &[usize]) -> Result<Vec<Ast>, String> {
                let mut found = Vec::new();
                for &id in ids { found.extend(map_node(tree, id)?); }
                Ok(found)
            }
            """);
        if (hasValues(ir)) {
            out.append("""

                fn map_values(tree: &Tree, ids: &[usize]) -> Result<Vec<AstValue>, String> {
                    let mut found = Vec::new();
                    for &id in ids {
                        let node = &tree.nodes[id];
                        match node.rule {
                            unlaxer_runtime::TEXT_VALUE_RULE => found.push(AstValue::Text {
                                text: unlaxer_runtime::java_capture_text(tree.text(node.span)).to_owned(),
                                span: node.span,
                            }),
                            unlaxer_runtime::VALUE_BOUNDARY_RULE => {
                                let values = map_values(tree, &node.children)?;
                                if !values.is_empty() && values.iter().all(|value| matches!(value, AstValue::Text { .. })) {
                                    found.push(AstValue::Text {
                                        text: unlaxer_runtime::java_capture_text(tree.text(node.span)).to_owned(),
                                        span: node.span,
                                    });
                                } else {
                                    found.extend(values);
                                }
                            },
                """);
            List<String> ids = new ArrayList<>();
            for (int i = 0; i < ir.rules().size(); i++) if (ir.rules().get(i).mapping() != null) ids.add(Integer.toString(i));
            out.append("            ").append(String.join(" | ", ids))
                .append(" => found.extend(map_node(tree, id)?.into_iter().map(|node| AstValue::Node(Box::new(node)))),\n")
                .append("            _ => found.extend(map_values(tree, &node.children)?),\n        }\n    }\n    Ok(found)\n}\n");
        }
        if (ir.rules().stream().filter(r -> r.mapping() != null).flatMap(r -> r.mapping().fields().stream())
            .anyMatch(f -> f.cardinality() == Cardinality.OPTIONAL)) out.append("""

            fn optional<T>(mut values: Vec<T>, name: &str) -> Result<Option<T>, String> {
                if values.len() > 1 { return Err(format!("expected at most one value for {name}, got {}", values.len())); }
                Ok(values.pop())
            }
            """);
        out.append("""

            fn map_node(tree: &Tree, id: usize) -> Result<Vec<Ast>, String> {
                match tree.nodes[id].rule {
            """);
        for (int i = 0; i < ir.rules().size(); i++) if (ir.rules().get(i).mapping() != null) {
            out.append("        ").append(i).append(" => map_rule_").append(i).append("(tree, id),\n");
        }
        out.append("        _ => map_nodes(tree, &tree.nodes[id].children),\n    }\n}\n");
        for (int i = 0; i < ir.rules().size(); i++) if (ir.rules().get(i).mapping() != null) {
            var mapping = ir.rules().get(i).mapping();
            out.append("\n#[inline(never)]\nfn map_rule_").append(i)
                .append("(tree: &Tree, id: usize) -> Result<Vec<Ast>, String> {\n")
                .append("    let node = &tree.nodes[id];\n")
                .append("    Ok(vec![Ast::r#").append(mapping.name()).append(" {\n        span: node.span,\n");
            for (Field field : mapping.fields()) {
                out.append("        r#").append(field.name()).append(": {\n            let mut values = Vec::new();\n")
                    .append("            for capture in node.captures.iter().filter(|c| c.name == ").append(quote(field.name())).append(") {\n");
                if (field.kind() == Kind.NODE) out.append("                values.extend(map_nodes(tree, &capture.nodes)?);\n");
                else if (field.kind() == Kind.VALUE) out.append("                values.extend(map_values(tree, &capture.nodes)?);\n");
                else out.append("                values.push(unlaxer_runtime::java_capture_text(tree.text(capture.span)).to_owned());\n");
                out.append("            }\n            ").append(mappedValue(field)).append("\n        },\n");
            }
            out.append("    }])\n}\n");
        }
        return out.toString();
    }

    private String evaluator(GrammarIR ir) {
        StringBuilder out = new StringBuilder(HEADER);
        if (hasValues(ir)) out.append("use super::ast::AstValue;\n");
        out.append("use super::ast::Ast;\nuse unlaxer_runtime::Span;\n\n#[allow(non_snake_case)]\npub trait Semantics {\n    type Output;\n");
        for (Mapping mapping : ir.mappings()) {
            out.append("    fn ").append(RustGrammarLowering.methodName(mapping.name())).append("(&mut self");
            for (Field field : mapping.fields()) out.append(", r#").append(field.name()).append(": ")
                .append(fieldType(field, true));
            out.append(", span: Span) -> Self::Output;\n");
        }
        out.append("}\n\n#[allow(non_snake_case)]\npub fn evaluate<S: Semantics>(node: &Ast, semantics: &mut S) -> S::Output {\n    match node {\n");
        for (Mapping mapping : ir.mappings()) {
            var args = new ArrayList<>(mapping.fields().stream().map(f -> "r#" + f.name()
                + (f.cardinality() == Cardinality.OPTIONAL ? (f.kind() == Kind.VALUE ? ".as_ref()" : ".as_deref()") : "")).toList());
            args.add("*span");
            out.append("        ").append(pattern(mapping, "Ast")).append(" => semantics.")
                .append(RustGrammarLowering.methodName(mapping.name())).append("(").append(String.join(", ", args)).append("),\n");
        }
        return out.append("    }\n}\n").toString();
    }

    private static String pattern(Mapping mapping, String type) {
        String fields = mapping.fields().stream().map(f -> ", r#" + f.name()).collect(Collectors.joining());
        return type + "::r#" + mapping.name() + " { span" + fields + " }";
    }

    private static String fieldType(Field field, boolean borrowed) {
        String one = switch (field.kind()) {
            case NODE -> borrowed ? "&Ast" : "Box<Ast>";
            case TEXT -> borrowed ? "&str" : "String";
            case VALUE -> borrowed ? "&AstValue" : "AstValue";
        };
        String element = switch (field.kind()) {
            case NODE -> "Ast";
            case TEXT -> "String";
            case VALUE -> "AstValue";
        };
        return switch (field.cardinality()) {
            case ONE -> one;
            case OPTIONAL -> "Option<" + one + ">";
            case MANY -> (borrowed ? "&[" : "Vec<") + element + (borrowed ? "]" : ">");
        };
    }

    private static String mappedValue(Field field) {
        return switch (field.cardinality()) {
            case ONE -> field.kind() == Kind.NODE ? "Box::new(required(values, " + quote(field.name()) + ")?)"
                : "required(values, " + quote(field.name()) + ")?";
            case OPTIONAL -> "optional(values, " + quote(field.name()) + ")?" + (field.kind() == Kind.NODE ? ".map(Box::new)" : "");
            case MANY -> "values";
        };
    }

    private static String fieldJson(Field field) {
        String name = "r#" + field.name();
        String value = field.kind() != Kind.TEXT ? "value.canonical_json()" : "json_string(value)";
        return switch (field.cardinality()) {
            case ONE -> field.kind() != Kind.TEXT ? name + ".canonical_json()" : "json_string(" + name + ")";
            case OPTIONAL -> name + ".as_ref().map_or_else(|| \"null\".to_owned(), |value| " + value + ")";
            case MANY -> "format!(\"[{}]\", " + name + ".iter().map(|value| " + value + ").collect::<Vec<_>>().join(\",\"))";
        };
    }

    private static boolean hasValues(GrammarIR ir) {
        return ir.mappings().stream().flatMap(mapping -> mapping.fields().stream()).anyMatch(field -> field.kind() == Kind.VALUE);
    }

    static String quote(String value) {
        StringBuilder out = new StringBuilder("\"");
        value.codePoints().forEach(c -> {
            switch (c) {
                case '"' -> out.append("\\\"");
                case '\\' -> out.append("\\\\");
                case '\n' -> out.append("\\n");
                case '\r' -> out.append("\\r");
                case '\t' -> out.append("\\t");
                default -> {
                    if (c < 32 || c == 127) out.append("\\u{").append(Integer.toHexString(c)).append('}');
                    else out.appendCodePoint(c);
                }
            }
        });
        return out.append('"').toString();
    }
}
