package org.unlaxer.dsl.codegen.rust;

import java.util.LinkedHashMap;
import static org.unlaxer.dsl.codegen.rust.GrammarIR.*;

/** Opt-in typed AST traversal, preserving each mapping's field declaration order. */
final class RustDapEmitter {
    private RustDapEmitter() {}
    static RustBackend.GeneratedFile generate(GrammarIR ir) {
        var out = new StringBuilder("// Generated by unlaxer RustBackend. Regenerate; do not edit.\n\n/// Strict typed AST nodes in mapping-field declaration order.\npub fn steps(source: &str) -> Result<Vec<unlaxer_dap::Step>, String> {\n    let tree = super::parser::parse_tree(source).map_err(|error| format!(\"{error:?}\"))?;\n    let ast = super::mapper::map(&tree)?;\n");
        var mappings = new LinkedHashMap<String,Mapping>();
        for (var rule : ir.rules()) if (rule.mapping() != null) mappings.putIfAbsent(rule.mapping().name(), rule.mapping());
        if (mappings.isEmpty()) out.append("    match ast {}\n}\n");
        else {
            out.append("    let mut out = Vec::new();\n    collect(&ast, &mut out);\n    Ok(out)\n}\n\nfn collect(node: &super::ast::Ast, out: &mut Vec<unlaxer_dap::Step>) {\n    match node {\n");
            for (var mapping : mappings.values()) {
                out.append("        super::ast::Ast::r#").append(mapping.name()).append(" { span");
                for (var field : mapping.fields()) if (field.kind() != Kind.TEXT) out.append(", r#").append(field.name());
                out.append(", .. } => {\n            out.push(unlaxer_dap::Step { label: ").append(RustBackend.quote(mapping.name())).append(".into(), span: *span });\n");
                for (var field : mapping.fields()) {
                    if (field.kind() == Kind.TEXT) continue;
                    String name = "r#" + field.name();
                    String body = field.kind() == Kind.NODE ? "collect(child, out);" : "if let super::ast::AstValue::Node(child) = child { collect(child, out); }";
                    String row = switch(field.cardinality()) {
                        case ONE -> "{ let child = " + name + "; " + body + " }";
                        case OPTIONAL -> "if let Some(child) = " + name + " { " + body + " }";
                        case MANY -> "for child in " + name + " { " + body + " }";
                    };
                    out.append("            ").append(row).append('\n');
                }
                out.append("        },\n");
            }
            out.append("    }\n}\n");
        }
        out.append("\npub fn backend() -> unlaxer_dap::AstBackend {\n    unlaxer_dap::AstBackend { mapper: steps }\n}\n\npub fn serve_stdio() -> std::io::Result<()> {\n    unlaxer_dap::Server::new(backend()).serve_stdio()\n}\n");
        return new RustBackend.GeneratedFile("dap.rs", out.toString());
    }
}
