package org.unlaxer.dsl.codegen.rust;

import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;
import org.unlaxer.dsl.bootstrap.UBNFAST.GrammarDecl;
import org.unlaxer.dsl.codegen.rust.GrammarIR.*;

/** Emits a Rust module, not a Cargo manifest or handwritten semantics. */
public final class RustBackend {
    public record GeneratedFile(String relativePath, String content) {}
    private static final String HEADER = "// Generated by unlaxer RustBackend. Regenerate; do not edit.\n";

    public List<GeneratedFile> generate(GrammarDecl grammar) {
        GrammarIR ir = RustGrammarLowering.lower(grammar);
        return List.of(
            new GeneratedFile("mod.rs", HEADER + """
                pub mod ast;
                pub mod parser;
                pub mod mapper;
                pub mod evaluator;
                """),
            new GeneratedFile("ast.rs", ast(ir)),
            new GeneratedFile("parser.rs", parser(ir)),
            new GeneratedFile("mapper.rs", mapper(ir)),
            new GeneratedFile("evaluator.rs", evaluator(ir)));
    }

    private String ast(GrammarIR ir) {
        StringBuilder out = new StringBuilder(HEADER);
        out.append("use unlaxer_runtime::{Span, json_string};\n\n#[allow(non_snake_case, non_camel_case_types)]\n#[derive(Debug, Clone, PartialEq)]\npub enum Ast {\n");
        for (Rule rule : ir.rules()) if (rule.mapping() != null) {
            var mapping = rule.mapping();
            out.append("    r#").append(mapping.name()).append(" { span: Span");
            for (Field field : mapping.fields()) out.append(", r#").append(field.name()).append(": ")
                .append(field.kind() == Kind.NODE ? "Box<Ast>" : "String");
            out.append(" },\n");
        }
        out.append("}\n\n#[allow(non_snake_case)]\nimpl Ast {\n    pub fn span(&self) -> Span {\n        match self {\n");
        for (Rule rule : ir.rules()) if (rule.mapping() != null) {
            out.append("            Self::r#").append(rule.mapping().name()).append(" { span, .. } => *span,\n");
        }
        out.append("        }\n    }\n\n    pub fn canonical_json(&self) -> String {\n        match self {\n");
        for (Rule rule : ir.rules()) if (rule.mapping() != null) {
            var mapping = rule.mapping();
            out.append("            ").append(pattern(mapping, "Self")).append(" => {\n");
            out.append("                let fields: Vec<String> = vec![\n");
            for (Field field : mapping.fields()) {
                out.append("                    format!(\"{}:{}\", json_string(").append(quote(field.name())).append("), ")
                    .append(field.kind() == Kind.NODE ? "r#" + field.name() + ".canonical_json()" : "json_string(r#" + field.name() + ")").append("),\n");
            }
            out.append("                ];\n                format!(\"{{\\\"type\\\":{},\\\"span\\\":[{},{}],\\\"fields\\\":{{{}}}}}\", json_string(")
                .append(quote(mapping.name())).append("), span.start, span.end, fields.join(\",\"))\n            },\n");
        }
        out.append("        }\n    }\n}\n");
        return out.toString();
    }

    private String parser(GrammarIR ir) {
        StringBuilder out = new StringBuilder(HEADER);
        out.append("""
            use unlaxer_runtime::{Expr, Rule, Tree, ParseError, ParseDiagnostic, ParseContext, ParseResult, Parser};

            pub struct GeneratedParser;

            impl Parser for GeneratedParser {
                fn parse(&self, context: &mut ParseContext<'_>) -> ParseResult {
                    parse_context(context)
                }
            }

            pub fn parse_tree(source: &str) -> Result<Tree, ParseError> {
                parse_tree_detailed(source).map_err(|diagnostic| diagnostic.farthest)
            }

            pub fn rules() -> Vec<Rule> {
                vec![
            """);
        for (Rule rule : ir.rules()) out.append("        Rule { name: ").append(quote(rule.name()))
            .append(", expression: ").append(expression(rule.body())).append(" },\n");
        out.append("    ]\n}\n\npub fn parse_context(context: &mut ParseContext<'_>) -> ParseResult {\n    context.parse_grammar(rules(), ")
            .append(ir.root()).append(", ").append(ir.javaWhitespace()).append(")\n}\n");
        out.append("\npub fn parse_tree_detailed(source: &str) -> Result<Tree, ParseDiagnostic> {\n    unlaxer_runtime::parse_detailed(&rules(), ")
            .append(ir.root()).append(", ").append(ir.javaWhitespace()).append(", source)\n}\n");
        return out.toString();
    }

    private String expression(Expression expression) {
        return switch (expression) {
            case Literal literal -> "Expr::Literal(" + quote(literal.text()) + ")";
            case NumberToken ignored -> "Expr::Number";
            case Reference reference -> "Expr::Rule(" + reference.rule() + ")";
            case Sequence sequence -> "Expr::Sequence(vec![" + expressions(sequence.elements()) + "])";
            case Choice choice -> "Expr::Choice(vec![" + expressions(choice.alternatives()) + "])";
            case Capture capture -> "Expr::Capture(" + quote(capture.name()) + ", Box::new(" + expression(capture.expression()) + "))";
        };
    }

    private String expressions(List<Expression> expressions) {
        return expressions.stream().map(this::expression).collect(Collectors.joining(", "));
    }

    private String mapper(GrammarIR ir) {
        StringBuilder out = new StringBuilder(HEADER);
        out.append("use super::ast::Ast;\nuse unlaxer_runtime::{Tree, Capture};\n\n");
        out.append("""
            pub fn map(tree: &Tree) -> Result<Ast, String> {
                map_node(tree, tree.root)?.ok_or_else(|| "no mapped root".to_owned())
            }

            fn capture<'a>(tree: &'a Tree, id: usize, name: &str) -> Result<&'a Capture, String> {
                let mut matches = tree.nodes[id].captures.iter().filter(|c| c.name == name);
                let result = matches.next().ok_or_else(|| format!("missing capture {name}"))?;
                if matches.next().is_some() { return Err(format!("duplicate capture {name}")); }
                Ok(result)
            }

            fn one_node(tree: &Tree, ids: &[usize]) -> Result<Option<Ast>, String> {
                let mut found = None;
                for &id in ids {
                    if let Some(node) = map_node(tree, id)? {
                        if found.is_some() { return Err("multiple mapped children".to_owned()); }
                        found = Some(node);
                    }
                }
                Ok(found)
            }

            fn map_node(tree: &Tree, id: usize) -> Result<Option<Ast>, String> {
                let node = &tree.nodes[id];
                match node.rule {
            """);
        for (int i = 0; i < ir.rules().size(); i++) if (ir.rules().get(i).mapping() != null) {
            var mapping = ir.rules().get(i).mapping();
            out.append("        ").append(i).append(" => Ok(Some(Ast::r#").append(mapping.name()).append(" {\n            span: node.span,\n");
            for (Field field : mapping.fields()) {
                String captured = "capture(tree, id, " + quote(field.name()) + ")?";
                out.append("            r#").append(field.name()).append(": ");
                if (field.kind() == Kind.NODE) out.append("Box::new(one_node(tree, &").append(captured)
                    .append(".nodes)?.ok_or_else(|| \"capture has no AST node\".to_owned())?)");
                else out.append("unlaxer_runtime::strip_capture(tree.text(").append(captured).append(".span)).to_owned()");
                out.append(",\n");
            }
            out.append("        })),\n");
        }
        out.append("        _ => one_node(tree, &node.children),\n    }\n}\n");
        return out.toString();
    }

    private String evaluator(GrammarIR ir) {
        StringBuilder out = new StringBuilder(HEADER);
        out.append("use super::ast::Ast;\nuse unlaxer_runtime::Span;\n\n#[allow(non_snake_case)]\npub trait Semantics {\n    type Output;\n");
        for (Rule rule : ir.rules()) if (rule.mapping() != null) {
            var mapping = rule.mapping();
            out.append("    fn ").append(RustGrammarLowering.methodName(mapping.name())).append("(&mut self");
            for (Field field : mapping.fields()) out.append(", r#").append(field.name()).append(": ")
                .append(field.kind() == Kind.NODE ? "&Ast" : "&str");
            out.append(", span: Span) -> Self::Output;\n");
        }
        out.append("}\n\n#[allow(non_snake_case)]\npub fn evaluate<S: Semantics>(node: &Ast, semantics: &mut S) -> S::Output {\n    match node {\n");
        for (Rule rule : ir.rules()) if (rule.mapping() != null) {
            var mapping = rule.mapping();
            var args = new ArrayList<>(mapping.fields().stream().map(f -> "r#" + f.name()).toList());
            args.add("*span");
            out.append("        ").append(pattern(mapping, "Ast")).append(" => semantics.")
                .append(RustGrammarLowering.methodName(mapping.name())).append("(").append(String.join(", ", args)).append("),\n");
        }
        return out.append("    }\n}\n").toString();
    }

    private static String pattern(Mapping mapping, String type) {
        String fields = mapping.fields().stream().map(f -> ", r#" + f.name()).collect(Collectors.joining());
        return type + "::r#" + mapping.name() + " { span" + fields + " }";
    }

    static String quote(String value) {
        StringBuilder out = new StringBuilder("\"");
        value.codePoints().forEach(c -> {
            switch (c) {
                case '"' -> out.append("\\\"");
                case '\\' -> out.append("\\\\");
                case '\n' -> out.append("\\n");
                case '\r' -> out.append("\\r");
                case '\t' -> out.append("\\t");
                default -> {
                    if (c < 32 || c == 127) out.append("\\u{").append(Integer.toHexString(c)).append('}');
                    else out.appendCodePoint(c);
                }
            }
        });
        return out.append('"').toString();
    }
}
